// <auto-generated />
using System;
using DataAccessLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(myContext))]
    [Migration("20230316114329_lab5-initial")]
    partial class lab5initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.DomainModels.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6d2abe1c-c0bc-43e5-a79b-c7467753c640"),
                            Name = "Electrical"
                        },
                        new
                        {
                            Id = new Guid("0924ac40-8cbe-46f6-bd0b-688bfc0e44c0"),
                            Name = "Mechanical"
                        },
                        new
                        {
                            Id = new Guid("40743094-348f-401e-ab04-00c3bd56afb4"),
                            Name = "Civil"
                        },
                        new
                        {
                            Id = new Guid("80701952-7ca2-4068-8070-2b543434b446"),
                            Name = "Petroleum"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.DomainModels.Developer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("developers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("86dd294e-11b0-42fd-8644-77b4e83b47e3"),
                            FirstName = "Jamal",
                            LastName = "Ali"
                        },
                        new
                        {
                            Id = new Guid("6467f76c-fc8c-4e82-9c8f-c6316b920c26"),
                            FirstName = "Mohamed",
                            LastName = "Magdy"
                        },
                        new
                        {
                            Id = new Guid("7d9ccc13-064d-482a-8faf-c0a9a8d8e59b"),
                            FirstName = "Mina",
                            LastName = "Gerges"
                        },
                        new
                        {
                            Id = new Guid("b5e8ac12-0c2d-4bad-a3ef-16e433357c59"),
                            FirstName = "Mahmoud",
                            LastName = "Hesham"
                        },
                        new
                        {
                            Id = new Guid("c0113a8a-e058-425b-9e30-40f7dcd3c9fd"),
                            FirstName = "Ahmed",
                            LastName = "Khairy"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.DomainModels.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("tickets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5cb4d103-bd27-4b67-b02f-f26560aa905b"),
                            Description = "ticket number one",
                            Severity = 2,
                            Title = "first"
                        },
                        new
                        {
                            Id = new Guid("8a549678-c889-4520-a582-bff12f66c4f5"),
                            Description = "ticket number two",
                            Severity = 1,
                            Title = "second"
                        },
                        new
                        {
                            Id = new Guid("9fdbaa65-e6d3-4a16-82b6-bfb9559452db"),
                            Description = "ticket number three",
                            Severity = 0,
                            Title = "third"
                        },
                        new
                        {
                            Id = new Guid("f835eff3-3aa9-4e17-85cf-45070902c258"),
                            Description = "ticket number four",
                            Severity = 2,
                            Title = "fourth"
                        });
                });

            modelBuilder.Entity("DeveloperTicket", b =>
                {
                    b.Property<Guid>("DevelopersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TicketsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DevelopersId", "TicketsId");

                    b.HasIndex("TicketsId");

                    b.ToTable("DeveloperTicket");
                });

            modelBuilder.Entity("DataAccessLayer.DomainModels.Ticket", b =>
                {
                    b.HasOne("DataAccessLayer.DomainModels.Department", "Department")
                        .WithMany("Tickets")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DeveloperTicket", b =>
                {
                    b.HasOne("DataAccessLayer.DomainModels.Developer", null)
                        .WithMany()
                        .HasForeignKey("DevelopersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.DomainModels.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.DomainModels.Department", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
